# Generated by Django 4.2 on 2024-05-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='settings'),
        ),
    ]
